# Enhanced dvc.yaml - Parameter templating for experiment versioning + statistical similarity
stages:
  preprocess:
    cmd: python -m sdpype.preprocess
    deps:
      - sdpype/preprocess.py
      - experiments/data/raw/
      - ${data.training_file}
      - ${data.metadata_file}
    params:
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/data/processed/data_${experiment.name}_${config_hash}_${experiment.seed}.csv
    metrics:
      - experiments/metrics/preprocess_${experiment.name}_${config_hash}_${experiment.seed}.json

  train_sdg:
    cmd: python -m sdpype.training
    deps:
      - sdpype/training.py
      - experiments/data/processed/data_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/processed/data_${experiment.name}_${config_hash}_${experiment.seed}_metadata.json
    params:
      - sdg
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/models/sdg_model_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/training_${experiment.name}_${config_hash}_${experiment.seed}.json

  generate_synthetic:
    cmd: python -m sdpype.generation
    deps:
      - sdpype/generation.py
      - experiments/models/sdg_model_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    params:
      - generation
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}.csv
    metrics:
      - experiments/metrics/generation_${experiment.name}_${config_hash}_${experiment.seed}.json

  statistical_similarity:
    cmd: python -m sdpype.evaluate
    deps:
      - sdpype/evaluate.py
      - sdpype/evaluation/statistical.py
      - experiments/data/processed/data_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/processed/data_${experiment.name}_${config_hash}_${experiment.seed}_metadata.json
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}.csv
    params:
      - evaluation
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/statistical_similarity_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/statistical_report_${experiment.name}_${config_hash}_${experiment.seed}.txt

  detection_evaluation:
    cmd: python -m sdpype.detect
    deps:
      - sdpype/detect.py
      - sdpype/evaluation/detection.py
      - experiments/data/processed/data_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/processed/data_${experiment.name}_${config_hash}_${experiment.seed}_metadata.json
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}.csv
    params:
      - evaluation.detection_evaluation
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/detection_evaluation_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/detection_report_${experiment.name}_${config_hash}_${experiment.seed}.txt
