stages:
  encode_training:
    cmd: python -m sdpype.encode_training
    deps:
      - sdpype/encode_training.py
      - sdpype/encoding.py
      - ${data.training_file}
      - ${encoding.config_file}
    params:
      - encoding
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/data/encoded/training_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/decoded/training_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/models/training_encoder_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/encoding_training_${experiment.name}_${config_hash}_${experiment.seed}.json

  train_sdg:
    cmd: python -m sdpype.training
    deps:
      - sdpype/training.py
      - ${data.training_file}
      - ${data.metadata_file}
      - experiments/models/training_encoder_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    params:
      - sdg
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/models/sdg_model_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/training_${experiment.name}_${config_hash}_${experiment.seed}.json

  generate_synthetic:
    cmd: python -m sdpype.generation
    deps:
      - sdpype/generation.py
      - ${data.reference_file}
      - experiments/models/sdg_model_${experiment.name}_${config_hash}_${experiment.seed}.pkl
      - experiments/models/training_encoder_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    params:
      - generation
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}_encoded.csv
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}_decoded.csv
    metrics:
      - experiments/metrics/generation_${experiment.name}_${config_hash}_${experiment.seed}.json

  encode_evaluation:
    cmd: python -m sdpype.encode_evaluation
    deps:
      - sdpype/encode_evaluation.py
      - sdpype/encoding.py
      - ${data.reference_file}
      - ${encoding.config_file}
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}_decoded.csv
    params:
      - encoding
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/data/encoded/reference_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/decoded/reference_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/encoded/synthetic_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/decoded/synthetic_${experiment.name}_${config_hash}_${experiment.seed}_decoded.csv
      - experiments/models/evaluation_encoder_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/encoding_evaluation_${experiment.name}_${config_hash}_${experiment.seed}.json

  statistical_similarity:
    cmd: python -m sdpype.evaluate
    deps:
      - sdpype/evaluate.py
      - sdpype/evaluation/statistical.py
      - ${data.reference_file}
      - ${data.metadata_file}
      - experiments/data/encoded/reference_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/decoded/reference_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/encoded/synthetic_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}_decoded.csv
    params:
      - evaluation
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/statistical_similarity_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/statistical_report_${experiment.name}_${config_hash}_${experiment.seed}.txt

  privacy_evaluation:
    cmd: python -m sdpype.privacy_evaluation
    deps:
      - sdpype/privacy_evaluation.py
      - sdpype/evaluation/statistical.py
      - ${data.reference_file}
      - ${data.metadata_file}
      - experiments/data/encoded/reference_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/decoded/reference_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/encoded/synthetic_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}_decoded.csv
    params:
      - evaluation.privacy
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/privacy_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/privacy_report_${experiment.name}_${config_hash}_${experiment.seed}.txt

  detection_evaluation:
    cmd: python -m sdpype.detect
    deps:
      - sdpype/detect.py
      - sdpype/evaluation/detection.py
      - ${data.reference_file}
      - ${data.metadata_file}
      - experiments/data/encoded/reference_${experiment.name}_${config_hash}_${experiment.seed}.csv
      - experiments/data/encoded/synthetic_${experiment.name}_${config_hash}_${experiment.seed}.csv
    params:
      - evaluation.detection_evaluation
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/detection_evaluation_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/detection_report_${experiment.name}_${config_hash}_${experiment.seed}.txt

  hallucination_evaluation:
    cmd: python -m sdpype.hallucination_evaluation
    deps:
      - sdpype/hallucination_evaluation.py
      - sdpype/evaluation/hallucination.py
      - ${data.population_file}
      - ${data.training_file}
      - ${data.metadata_file}
      - ${evaluation.hallucination.query_file}
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}_decoded.csv
    params:
      - evaluation.hallucination
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/hallucination_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/hallucination_report_${experiment.name}_${config_hash}_${experiment.seed}.txt
