# Enhanced dvc.yaml - Parameter templating for experiment versioning
stages:
  preprocess:
    cmd: python -m sdpype.preprocess
    deps:
      - sdpype/preprocess.py
      - experiments/data/raw/
      - config/preprocessing/
    params:
      - experiment.seed
    outs:
      - experiments/data/processed/data_${experiment.seed}.csv
    metrics:
      - experiments/metrics/preprocess_${experiment.seed}.json

  train_sdg:
    cmd: python -m sdpype.training
    deps:
      - sdpype/training.py
      - experiments/data/processed/data_${experiment.seed}.csv
      - config/sdg/
    params:
      - sdg
      - experiment.seed
    outs:
      - experiments/models/sdg_model_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/training_${experiment.seed}.json

  generate_synthetic:
    cmd: python -m sdpype.generation
    deps:
      - sdpype/generation.py
      - experiments/models/sdg_model_${experiment.seed}.pkl
      - config/
    params:
      - generation
      - experiment.seed
    outs:
      - experiments/data/synthetic/synthetic_data_${experiment.seed}.csv
    metrics:
      - experiments/metrics/generation_${experiment.seed}.json