# Simplified dvc.yaml - Using params.yaml for DVC experiments
stages:
  preprocess:
    cmd: python -m sdpype.preprocess
    deps:
      - sdpype/preprocess.py
      - experiments/data/raw/
      - config/preprocessing/
    params:
      - experiment.seed
    outs:
      - experiments/data/processed/data.csv
    metrics:
      - experiments/metrics/preprocess.json

  train_sdg:
    cmd: python -m sdpype.training
    deps:
      - sdpype/training.py
      - experiments/data/processed/data.csv
      - config/sdg/
    params:
      - sdg
      - experiment.seed
    outs:
      - experiments/models/sdg_model.pkl
    metrics:
      - experiments/metrics/training.json

  generate_synthetic:
    cmd: python -m sdpype.generation
    deps:
      - sdpype/generation.py
      - experiments/models/sdg_model.pkl
      - config/
    params:
      - generation
      - experiment.seed
    outs:
      - experiments/data/synthetic/synthetic_data.csv
    metrics:
      - experiments/metrics/generation.json
