# Enhanced dvc.yaml - Parameter templating for experiment versioning + statistical similarity
stages:
  preprocess:
    cmd: python -m sdpype.preprocess
    deps:
      - sdpype/preprocess.py
      - experiments/data/raw/
    params:
      - experiment.seed
    outs:
      - experiments/data/processed/data_${experiment.seed}.csv
    metrics:
      - experiments/metrics/preprocess_${experiment.seed}.json

  train_sdg:
    cmd: python -m sdpype.training
    deps:
      - sdpype/training.py
      - experiments/data/processed/data_${experiment.seed}.csv
    params:
      - sdg
      - experiment.seed
    outs:
      - experiments/models/sdg_model_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/training_${experiment.seed}.json

  generate_synthetic:
    cmd: python -m sdpype.generation
    deps:
      - sdpype/generation.py
      - experiments/models/sdg_model_${experiment.seed}.pkl
    params:
      - generation
      - experiment.seed
    outs:
      - experiments/data/synthetic/synthetic_data_${experiment.seed}.csv
    metrics:
      - experiments/metrics/generation_${experiment.seed}.json

  evaluate_original:
    cmd: python -m sdpype.evaluate +evaluation_data_type=original
    deps:
      - sdpype/evaluate.py
      - sdpype/evaluation/
      - experiments/data/processed/data_${experiment.seed}.csv
    params:
      - evaluation
      - experiment.seed
    metrics:
      - experiments/metrics/quality_original_${experiment.seed}.json

  evaluate_synthetic:
    cmd: python -m sdpype.evaluate +evaluation_data_type=synthetic
    deps:
      - sdpype/evaluate.py
      - sdpype/evaluation/
      - experiments/data/synthetic/synthetic_data_${experiment.seed}.csv
    params:
      - evaluation
      - experiment.seed
    metrics:
      - experiments/metrics/quality_synthetic_${experiment.seed}.json

  # 🔬 ENHANCED EVALUATION STAGE - Now includes statistical similarity
  compare_quality:
    cmd: python -m sdpype.evaluate +evaluation_data_type=both
    deps:
      - sdpype/evaluate.py
      - sdpype/evaluation/intrinsic.py
      - sdpype/evaluation/statistical.py        # ✨ NEW DEPENDENCY
      - experiments/data/processed/data_${experiment.seed}.csv      # ✨ NEW - needed for statistical comparison
      - experiments/data/synthetic/synthetic_data_${experiment.seed}.csv  # ✨ NEW - needed for statistical comparison
      - experiments/metrics/quality_original_${experiment.seed}.json
      - experiments/metrics/quality_synthetic_${experiment.seed}.json
    params:
      - evaluation
      - experiment.seed
    metrics:
      - experiments/metrics/quality_comparison_${experiment.seed}.json
      - experiments/metrics/statistical_similarity_${experiment.seed}.json  # ✨ NEW OUTPUT
      - experiments/metrics/statistical_report_${experiment.seed}.txt       # ✨ NEW OUTPUT
