# Enhanced dvc.yaml - Parameter templating for experiment versioning + statistical similarity
stages:
  preprocess:
    cmd: python -m sdpype.preprocess
    deps:
      - sdpype/preprocess.py
      - experiments/data/raw/
    params:
      - experiment.seed
      - experiment.name
    outs:
      - experiments/data/processed/data_${experiment.name}_${experiment.seed}.csv
    metrics:
      - experiments/metrics/preprocess_${experiment.name}_${experiment.seed}.json

  train_sdg:
    cmd: python -m sdpype.training
    deps:
      - sdpype/training.py
      - experiments/data/processed/data_${experiment.name}_${experiment.seed}.csv
      - experiments/data/processed/data_${experiment.name}_${experiment.seed}_metadata.json
    params:
      - sdg
      - experiment.seed
      - experiment.name
    outs:
      - experiments/models/sdg_model_${experiment.name}_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/training_${experiment.name}_${experiment.seed}.json

  generate_synthetic:
    cmd: python -m sdpype.generation
    deps:
      - sdpype/generation.py
      - experiments/models/sdg_model_${experiment.name}_${experiment.seed}.pkl
    params:
      - generation
      - experiment.seed
      - experiment.name
    outs:
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${experiment.seed}.csv
    metrics:
      - experiments/metrics/generation_${experiment.name}_${experiment.seed}.json

  statistical_similarity:
    cmd: python -m sdpype.evaluate
    deps:
      - sdpype/evaluate.py
      - sdpype/evaluation/statistical.py
      - experiments/data/processed/data_${experiment.name}_${experiment.seed}.csv
      - experiments/data/processed/data_${experiment.name}_${experiment.seed}_metadata.json
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${experiment.seed}.csv
    params:
      - evaluation
      - experiment.seed
      - experiment.name
    metrics:
      - experiments/metrics/statistical_similarity_${experiment.name}_${experiment.seed}.json
      - experiments/metrics/statistical_report_${experiment.name}_${experiment.seed}.txt
