stages:
  train_sdg:
    cmd: python -m sdpype.training
    deps:
      - sdpype/training.py
      - ${data.training_file}
      - ${data.metadata_file}
    params:
      - sdg
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/models/sdg_model_${experiment.name}_${config_hash}_${experiment.seed}.pkl
    metrics:
      - experiments/metrics/training_${experiment.name}_${config_hash}_${experiment.seed}.json

  generate_synthetic:
    cmd: python -m sdpype.generation
    deps:
      - sdpype/generation.py
      - ${data.reference_file}
    params:
      - generation
      - experiment.seed
      - experiment.name
      - config_hash
    outs:
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}.csv
    metrics:
      - experiments/metrics/generation_${experiment.name}_${config_hash}_${experiment.seed}.json

  statistical_similarity:
    cmd: python -m sdpype.evaluate
    deps:
      - sdpype/evaluate.py
      - sdpype/evaluation/statistical.py
      - ${data.reference_file}
      - ${data.metadata_file}
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}.csv
    params:
      - evaluation
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/statistical_similarity_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/statistical_report_${experiment.name}_${config_hash}_${experiment.seed}.txt

  detection_evaluation:
    cmd: python -m sdpype.detect
    deps:
      - sdpype/detect.py
      - sdpype/evaluation/detection.py
      - ${data.reference_file}
      - ${data.metadata_file}
      - experiments/data/synthetic/synthetic_data_${experiment.name}_${config_hash}_${experiment.seed}.csv
    params:
      - evaluation.detection_evaluation
      - experiment.seed
      - experiment.name
      - config_hash
    metrics:
      - experiments/metrics/detection_evaluation_${experiment.name}_${config_hash}_${experiment.seed}.json
      - experiments/metrics/detection_report_${experiment.name}_${config_hash}_${experiment.seed}.txt
