# DVC-Compatible params.yaml - No Hydra interpolation, works with DVC experiments

# =============================================================================
# EXPERIMENT CONFIGURATION
# =============================================================================
experiment:
  seed: 42
  generation: 0
  name: "{sdg.library}_{sdg.model_type}_{data.reference_hash}_{data.root_hash}_{data.training_hash}_gen_{experiment.generation}"
  description: "Testing"
  researcher: test_user
  tags:

# =============================================================================
# ACTIVE MODEL CONFIGURATION - Edit here or override with DVC
# =============================================================================
sdg:
  library: sdv
  model_type: ctgan
  parameters: {}

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  training_file: experiments/data/processed/trn_sample_data.csv
  reference_file: experiments/data/processed/ref_sample_data.csv
  metadata_file: experiments/data/processed/sample_data_metadata.json

# =============================================================================
# ENCODING CONFIGURATION
# =============================================================================
encoding:
  # Path to RDT encoding configuration YAML file
  # This file specifies transformers for each column
  config_file: experiments/configs/encoding/example_covid.yaml

  # Whether to enable encoding stage (set to false to skip encoding)
  enabled: true

# =============================================================================
# GENERATION SETTINGS
# =============================================================================
generation:
  n_samples:       # Number of synthetic samples to generate # Set to null to match original dataset size

# =============================================================================
# STATISTICAL SIMILARITY EVALUATION CONFIGURATION
# =============================================================================
evaluation:
  statistical_similarity:
    metrics:
    - name: table_structure
      parameters: {}
    - name: boundary_adherence
      parameters:
        target_columns:
    - name: category_adherence
      parameters:
        target_columns:
    - name: "alpha_precision"
      parameters: {}
    - name: "prdc_score"
      parameters:
        nearest_k: 5
    - name: "wasserstein_distance"
      parameters: {}
    - name: "maximum_mean_discrepancy"
      parameters:
        kernel: rbf  # Options: rbf, linear, polynomial      
    - name: "new_row_synthesis"
      parameters:
        numerical_match_tolerance: 0.01
        synthetic_sample_size:
    - name: "jensenshannon_synthcity"
      parameters:
        normalize: true
        n_histogram_bins: 10
    - name: "jensenshannon_syndat"
      parameters:
        n_unique_threshold: 10
    - name: "jensenshannon_nannyml"
      parameters: {}  # Uses adaptive Doane's formula binning
    - name: "ks_complement"
      parameters:
        target_columns:
    - name: "tv_complement"
      parameters:
        target_columns:

# Detection-based evaluation using classifier approaches
  detection_evaluation:
    # Common parameters for all detection methods (synthcity DetectionEvaluator params)
    common_params:
      n_folds: 5              # Cross-validation folds
      random_state: 51        # Random seed
      reduction: "max"        # Aggregation: "mean", "max", "min"

    methods:
    - name: "detection_gmm"
      parameters: {}
           # Override common params if needed
           # n_folds: 3
    - name: "detection_xgb"
      parameters: {}
           # Override common params if needed
           # reduction: "max"
    - name: "detection_mlp"
      parameters: {}
           # Override common params if needed
    - name: "detection_linear"
      parameters: {}
            # Override common params if needed
