# DVC-Compatible params.yaml - No Hydra interpolation, works with DVC experiments

# =============================================================================
# EXPERIMENT CONFIGURATION
# =============================================================================
experiment:
  seed: 3
  name: synthcity_ctgan_baseline
  description: Using synthcity ctgan with default settings
  researcher: anonymous
  tags: []

# =============================================================================
# ACTIVE MODEL CONFIGURATION - Edit here or override with DVC
# =============================================================================
sdg:
  library: synthcity
  model_type: ctgan
  parameters: {}

# =============================================================================
# PREPROCESSING CONFIGURATION
# =============================================================================

preprocessing:
  enabled: true
  steps:
    encode_categorical: label
    handle_missing: mean
    remove_outliers: true
    scale_numeric: standard

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  input_file: experiments/data/raw/sample_data.csv
  metadata_file: experiments/data/raw/sample_data_metadata.json

# =============================================================================
# GENERATION SETTINGS
# =============================================================================
generation:
  n_samples:       # Number of synthetic samples to generate # Set to null to match original dataset size

# =============================================================================
# STATISTICAL SIMILARITY EVALUATION CONFIGURATION
# =============================================================================
evaluation:
  statistical_similarity:
    metrics:
    - name: table_structure
      parameters: {}
    - name: boundary_adherence
      parameters:
        target_columns:
    - name: category_adherence
      parameters:
        target_columns:
    - name: "alpha_precision"
      parameters: {}
    - name: "prdc_score"
      parameters:
        nearest_k: 5
    - name: "new_row_synthesis"
      parameters:
        numerical_match_tolerance: 0.01
        synthetic_sample_size:
    - name: "ks_complement"
      parameters:
        target_columns:
    - name: "tv_complement"
      parameters:
        target_columns:
