# DVC-Compatible params.yaml - No Hydra interpolation, works with DVC experiments

# =============================================================================
# EXPERIMENT CONFIGURATION
# =============================================================================
experiment:
  seed: 123
  name: sdv_tvae_test
  description: SDPype synthetic data generation experiment
  researcher: anonymous
  tags: []

# =============================================================================
# ACTIVE MODEL CONFIGURATION - Edit here or override with DVC
# =============================================================================
sdg:
  library: sdv
  model_type: copula_gan
  parameters:
    enforce_min_max_values: True
    enforce_rounding: True
    locales: ['en_US']
    default_distribution: beta
    numerical_distributions:
      age: 'gaussian_kde'
      score: 'gaussian_kde'
    epochs: 300
    cuda: True
    verbose: True
    batch_size: 500
    discriminator_dim:
      - 256
      - 256
    discriminator_decay: 1e-06
    discriminator_lr: 0.0002
    discriminator_steps: 1
    embedding_dim: 128
    generator_decay: 1e-06
    generator_dim:
      - 256
      - 256
    generator_lr: 0.0002
    log_frequency: True
    pac: 10

# =============================================================================
# PREPROCESSING CONFIGURATION
# =============================================================================

preprocessing:
  enabled: true
  steps:
    encode_categorical: label
    handle_missing: mean
    remove_outliers: true
    scale_numeric: standard

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  input_file: experiments/data/raw/sample_data.csv

# =============================================================================
# GENERATION SETTINGS
# =============================================================================
generation:
  n_samples: null  # Number of synthetic samples to generate # Set to null to match original dataset size

# =============================================================================
# STATISTICAL SIMILARITY EVALUATION CONFIGURATION
# =============================================================================
evaluation:
  statistical_similarity:
    metrics:
      - name: "alpha_precision"
        parameters: {}
      - name: "prdc_score"
        parameters:
          nearest_k: 5
