# DVC-Compatible params.yaml - No Hydra interpolation, works with DVC experiments

# =============================================================================
# EXPERIMENT CONFIGURATION
# =============================================================================
experiment:
  seed: 43
  name: sdpype_experiment
  description: SDPype synthetic data generation experiment
  researcher: anonymous
  tags: []

# =============================================================================
# ACTIVE MODEL CONFIGURATION - Edit here or override with DVC
# =============================================================================
sdg:
  library: synthcity
  model_type: ctgan
  parameters:
    n_iter: 300

# =============================================================================
# PREPROCESSING CONFIGURATION
# =============================================================================
preprocessing:
  enabled: true
  steps:
    handle_missing: mean
    remove_outliers: true
    scale_numeric: standard

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  input_file: experiments/data/raw/sample_data.csv

# =============================================================================
# GENERATION SETTINGS
# =============================================================================
generation:
  n_samples: 1000

# =============================================================================
# EVALUATION CONFIGURATION
# =============================================================================
evaluation:
  intrinsic_quality:
    evaluate_original: true
    evaluate_synthetic: true
    comparative_analysis: true
  statistical_similarity:
    enabled: true
  downstream_tasks:
    enabled: false
