# Complete standalone params.yaml - No defaults needed
experiment:
  seed: 100
  name: sdpype_experiment
  description: SDPype experiment
  researcher: anonymous
  tags: []

# Data configuration
data:
  input_file: experiments/data/raw/sample_data.csv

# Preprocessing configuration (inline, no defaults)
preprocessing:
  enabled: true
  steps:
    handle_missing: mean
    remove_outliers: true
    scale_numeric: standard

# SDG configuration (inline, no defaults)
sdg:
  library: sdv
  model_type: ctgan
  parameters:
    epochs: 300     # Add default epochs parameter
    batch_size: 500 # Add default batch_size parameter

# Generation configuration
generation:
  n_samples: 1000

evaluation:
  intrinsic_quality:
    evaluate_original: true
    evaluate_synthetic: true
    comparative_analysis: true
  statistical_similarity:
    enabled: false
  downstream_tasks:
    enabled: false

# Hydra settings
hydra:
  job:
    chdir: false
