# DVC-Compatible params.yaml - No Hydra interpolation, works with DVC experiments

# =============================================================================
# EXPERIMENT CONFIGURATION
# =============================================================================
experiment:
  seed: 1
  name: sdv_gaussian_copula_baseline
  description: Using SDV gaussian copula with default settings (baseline)
  researcher: anonymous
  tags: []

# =============================================================================
# ACTIVE MODEL CONFIGURATION - Edit here or override with DVC
# =============================================================================
sdg:
  library: sdv
  model_type: gaussian_copula
  parameters: {}

# =============================================================================
# PREPROCESSING CONFIGURATION
# =============================================================================

preprocessing:
  enabled: true
  steps:
    encode_categorical: label
    handle_missing: mean
    remove_outliers: true
    scale_numeric: standard

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  input_file: experiments/data/raw/sample_data.csv
  metadata_file: experiments/data/raw/sample_data_metadata.json

# =============================================================================
# GENERATION SETTINGS
# =============================================================================
generation:
  n_samples: null  # Number of synthetic samples to generate # Set to null to match original dataset size

# =============================================================================
# STATISTICAL SIMILARITY EVALUATION CONFIGURATION
# =============================================================================
evaluation:
  statistical_similarity:
    metrics:
      - name: table_structure
        parameters: {}
      - name: boundary_adherence
        parameters:
          target_columns: null
      - name: category_adherence
        parameters:
          target_columns: null
      - name: "alpha_precision"
        parameters: {}
      - name: "prdc_score"
        parameters:
          nearest_k: 5
      - name: "new_row_synthesis"
        parameters:
          numerical_match_tolerance: 0.01
          synthetic_sample_size: null
      - name: "ks_complement"
        parameters:
          target_columns: null
      - name: "tv_complement"
        parameters:
          target_columns: null