# DVC-Compatible params.yaml - No Hydra interpolation, works with DVC experiments

# =============================================================================
# EXPERIMENT CONFIGURATION
# =============================================================================
experiment:
  seed: 456
  name: synthcity_bayesian_network_test
  description: Testing enhanced synthcity Bayesian Network with custom structure learning
  researcher: test_user
  tags: ["synthcity", "bayesian_network", "probabilistic", "enhanced", "test"]

# =============================================================================
# ACTIVE MODEL CONFIGURATION - Edit here or override with DVC
# =============================================================================
sdg:
  library: synthcity
  model_type: bayesian_network
  parameters:
    # Structure learning parameters (different from defaults to verify they're used)
    struct_learning_n_iter: 500  # Reduced for testing (default: 1000)
    struct_learning_search_method: "hillclimb"  # Different from default (default: "tree_search")
    struct_learning_score: "bic"  # Different from default (default: "k2")
    struct_max_indegree: 3  # Lower than default (default: 4)

    # Data encoding parameters (test custom encoding)
    encoder_max_clusters: 15  # Higher than default (default: 10)
    encoder_noise_scale: 0.05  # Lower than default (default: 0.1)

    # Core plugin settings
    random_state: 456  # Match experiment seed
    compress_dataset: True  # Different from default (default: False)
    sampling_patience: 200  # Reduced for testing (default: 500)

# =============================================================================
# PREPROCESSING CONFIGURATION
# =============================================================================

preprocessing:
  enabled: true
  steps:
    encode_categorical: label
    handle_missing: mean
    remove_outliers: true
    scale_numeric: standard

# =============================================================================
# DATA CONFIGURATION
# =============================================================================
data:
  input_file: experiments/data/raw/sample_data.csv
  metadata_file: experiments/data/raw/sample_data_metadata.json

# =============================================================================
# GENERATION SETTINGS
# =============================================================================
generation:
  n_samples:       # Number of synthetic samples to generate # Set to null to match original dataset size

# =============================================================================
# STATISTICAL SIMILARITY EVALUATION CONFIGURATION
# =============================================================================
evaluation:
  statistical_similarity:
    metrics:
    - name: table_structure
      parameters: {}
    - name: boundary_adherence
      parameters:
        target_columns:
    - name: category_adherence
      parameters:
        target_columns:
    - name: "alpha_precision"
      parameters: {}
    - name: "prdc_score"
      parameters:
        nearest_k: 5
    - name: "new_row_synthesis"
      parameters:
        numerical_match_tolerance: 0.01
        synthetic_sample_size:
    - name: "ks_complement"
      parameters:
        target_columns:
    - name: "tv_complement"
      parameters:
        target_columns:
