# Enhanced evaluation configuration with statistical similarity
intrinsic_quality:
  evaluate_original: true
  evaluate_synthetic: true
  comparative_analysis: true

statistical_similarity:
  enabled: true  # 🎯 NOW ENABLED for Type 2 evaluation

downstream_tasks:
  enabled: false  # Future extension

# Output settings
save_plots: false  # Future extension
report_format: "json"
