# Basic evaluation configuration
intrinsic_quality:
  evaluate_original: true
  evaluate_synthetic: true
  comparative_analysis: true

statistical_similarity:
  enabled: false  # Will add in next phase

downstream_tasks:
  enabled: false  # Will add in next phase

# Output settings
save_plots: false  # Will add in next phase
report_format: "json"
