# config/config.yaml - Main config
defaults:
  - preprocessing: standard
  - sdg: gaussian
  - _self_

experiment:
  name: "sdpype_experiment"
  seed: 42

data:
  input_file: "data/raw/sample_data.csv"
  
generation:
  n_samples: 1000

# Hydra settings
hydra:
  job:
    chdir: false
